In [7]:

import jax
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

key = random.PRNGKey(0)


w = jax.random.uniform(key, shape=(2, 2))   # 2*2 权重

b = jax.random.uniform(key, shape=(2, 2))   # 2*2 偏置

x = jnp.array(
    [ [11, 12], 
      [21, 22] ]
    ) 

p =  jnp.array(
    [ [1, 0], 
      [0, 1] ]
    ) 

def A(x, w, b):
  x11 = x[0][0]
  x12 = x[0][1]
  x21 = x[1][0]
  x22 = x[1][1]

  w11 = w[0][0]
  w12 = w[0][1]
  w21 = w[1][0]
  w22 = w[1][1]

  b11 = b[0][0]
  b12 = b[0][1]
  b21 = b[1][0]
  b22 = b[1][1]

  a11 = x11*w11 + x12*w21 + b11

  a12 = x11*w12 + x12*w22 + b12

  a21 = x21*w11 + x22*w21 + b21

  a22 = x21*w12 + x22*w22 + b22

  a = ( (a11, a12), (a21, a22) )

  return a


jac_w = jax.jacfwd(lambda xx: A(x, xx, b) )(w)  # A 对w 的偏导（雅可比矩阵）
jac_b = jax.jacfwd(lambda xx: A(x, w, xx) )(b) 


print(jac_w)
print(jac_b)

#a = A(x, w, b)

#print(a)




((DeviceArray([[11.,  0.],
             [12.,  0.]], dtype=float32), DeviceArray([[ 0., 11.],
             [ 0., 12.]], dtype=float32)), (DeviceArray([[21.,  0.],
             [22.,  0.]], dtype=float32), DeviceArray([[ 0., 21.],
             [ 0., 22.]], dtype=float32)))
((DeviceArray([[1., 0.],
             [0., 0.]], dtype=float32), DeviceArray([[0., 1.],
             [0., 0.]], dtype=float32)), (DeviceArray([[0., 0.],
             [1., 0.]], dtype=float32), DeviceArray([[0., 0.],
             [0., 1.]], dtype=float32)))


In [ ]:
# https://www.geeksforgeeks.org/jacobian-matrix-in-pytorch/
from torch.autograd.functional import jacobian
from torch import tensor
 
#Defining the main function
def f(x1,x2,x3):
    return (x1 + x2, x3*x1, x2**3)
 
#Defining input tensors
x1 = tensor(3.0)
x2 = tensor(4.0)
x3 = tensor(5.0)
 
#Printing the Jacobian
print(jacobian(f,(x1,x2,x3)))

((tensor(1.), tensor(1.), tensor(0.)), (tensor(5.), tensor(0.), tensor(3.)), (tensor(0.), tensor(48.), tensor(0.)))


In [ ]:
from torch.autograd.functional import jacobian
from torch import tensor
 
#Defining the main function
def f(x):
    return (x[0]+ x[1], x[2]*x[0], x[1]**3)
 
#Defining input tensors
x1 = tensor(3.0)
x2 = tensor(4.0)
x3 = tensor(5.0)

x  = tensor( [3., 4. , 5.] )
 
#Printing the Jacobian
print(jacobian(f,x ))

(tensor([1., 1., 0.]), tensor([5., 0., 3.]), tensor([ 0., 48.,  0.]))


In [ ]:
# https://github.com/google/jax/issues/47
import jax
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

def f(x1,x2,x3):
    return (x1 + x2, x3*x1, x2**3)

x1 = 3.
x2 = 4.
x3 = 5.

jac_x1 = jax.jacfwd(lambda x: f(x,x2,x3))(x1)
jac_x2 = jax.jacfwd(lambda x: f(x1,x,x3))(x2)
jac_x3 = jax.jacfwd(lambda x: f(x1,x2,x))(x3)

print(jac_x1)

#print(jac_x2)

#print(jac_x3)


(DeviceArray(1., dtype=float32), DeviceArray(5., dtype=float32), DeviceArray(0., dtype=float32))


In [ ]:

from torch.autograd.functional import jacobian
from torch import tensor
import torch

import numpy

x = tensor(
    [ [11, 12], 
      [21, 22] ]
    ) 

w = tensor( numpy.random.uniform(key, size=(2, 2)) )   # 2*2 权重
b = ( numpy.random.uniform(key, size=(2, 2)) )   # 2*2 偏置


def A(w):
  with torch.no_grad():
    return tensor( numpy.dot( x, w ) + b )

print(jacobian(A, w))


tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]], dtype=torch.float64)


In [ ]:

import jax
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

key = random.PRNGKey(0)


w = jax.random.uniform(key, shape=(2, 2))   # 2*2 权重

b = jax.random.uniform(key, shape=(2, 2))   # 2*2 偏置

x = jnp.array(
    [ [11, 12], 
      [21, 22] ]
    ) 

p =  jnp.array(
    [ [1, 0], 
      [0, 1] ]
    ) 

def A(w, b):
  return x.dot( w ) + b


jac_w = jax.jacfwd(lambda x: A(x, b))(w)
jac_b = jax.jacfwd(lambda x: A(w, x))(b)


print(jac_w)


# print(jac_b)


[[[[11.  0.]
   [12.  0.]]

  [[ 0. 11.]
   [ 0. 12.]]]


 [[[21.  0.]
   [22.  0.]]

  [[ 0. 21.]
   [ 0. 22.]]]]


In [ ]:
"""
{
 {
 {
{11. ,0.},
{12. , 0.}
},
{
	{0., 11.},
	{0. ,12.}
 }
} // MatrixForm  ,
{
  {
{21. ,0.},
{22., 0.}
},
{
	{0., 21.},
	{0. ,22.}
}
} //MatrixForm
} // MatrixForm


In[24]:= x = {{x11, x12},{x21, x22}}; x//MatrixForm
w = {{w11,w12}, {w21, w22}}; w//MatrixForm
Out[24]//MatrixForm= (x11	x12
x21	x22

)
Out[25]//MatrixForm= (w11	w12
w21	w22

)
In[28]:= a =x.w; a//MatrixForm
Out[28]//MatrixForm= (w11 x11+w21 x12	w12 x11+w22 x12
w11 x21+w21 x22	w12 x21+w22 x22

)


"""

In [ ]:
import jax
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

key = random.PRNGKey(0)


w = jax.random.uniform(key, shape=(2, 2))   # 2*2 权重

x = jnp.array(
    [ [0, 0], 
      [0, 1] ]
    ) 

p =  jnp.array(
    [ [1, 0], 
      [0, 1] ]
    ) 

# print( jnp.log( p ) )

#b = jax.random.uniform(key, shape=(2, 2))   # 2*2 偏置


def forword(w, b):
  a = x.dot( w ) + b
  q = jnp.exp(a - jnp.max(a))
  
  delta = 1e-7
  tmp = -1 * p * ( jnp.log( q + delta ) )
  e = jnp.sum(tmp, axis=1)
  return e.sum() * 0.5


#grad_forword = jax.jacfwd(forword)  # column-by-column
  # jacrev is row-by-row



for i in range(10000):

  #jac_w = grad_forword(w)
  #jac_b = grad_forword2(b)

  jac_w = jax.jacfwd(lambda x: forword(x, b))(w)
  jac_b = jax.jacfwd(lambda x: forword(w, x))(b)
  
  loss = forword(w, b)

  w = w - 0.01 * jac_w
  b = b - 0.01 * jac_b

  #print(loss)
  #print(jac_w)

  #if i == 9999:
  print(loss)


a = x.dot( w ) + b
q = jnp.exp(a - jnp.max(a))

print(p)
print(q)




In [ ]:
# https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html
# https://jax.readthedocs.io/en/latest/jax.html#jax.jacfwd   grad 只能对标量求导，jacfwd 对向量 

# https://stackoverflow.com/questions/63559139/efficient-way-to-compute-jacobian-x-jacobian-t

# Cross entropy  chain rule


# https://deepnotes.io/softmax-crossentropy

# https://mathematica.stackexchange.com/questions/5790/how-to-make-jacobian-automatically-in-mathematica

# https://www.geeksforgeeks.org/jacobian-matrix-in-pytorch/



In [ ]:

# import numpy as np
# import torch
# from torch import tensor

# from torch.autograd.functional import jacobian
# from torch.functional import Tensor

import jax
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

key = random.PRNGKey(0)


# def exp_reducer(x):
#     return x.exp() # .sum(dim=1)

# inputs =  Tensor( [ [1, 2], [3, 4] ] ) # torch.rand(2, 2)
# outputs = exp_reducer(inputs)

# ja = jacobian(exp_reducer, inputs)


w = jax.random.uniform(key, shape=(2, 2))   # 2*2 权重

x = jnp.array(
    [ [0, 0], 
      [0, 1] ]
    ) 

p =  jnp.array(
    [ [1, 0], 
      [0, 1] ]
    ) 

# print( jnp.log( p ) )

b = jax.random.uniform(key, shape=(2, 2))   # 2*2 偏置

def forword(w):

    # 前向传播 (2,2) . (2,2) = (2,2)

    a = x.dot( w ) + b

    return a

def stable_softmax(X):
    exps = jnp.exp(X - jnp.max(X))
    return exps / jnp.sum(exps)

def crossELoss(q):
    delta = 1e-7
    tmp = -1 * p * ( jnp.log( q + delta ) )
    e = jnp.sum(tmp, axis=1)
    return e.sum() * 0.5

# grad_forword = grad(forword) # grad 只能对标量求导

grad_forword = jax.jacfwd(forword)  # column-by-column
  # jacrev is row-by-row

grad_softmax = jax.jacfwd(stable_softmax) 

grad_crossE = jax.jacfwd(crossELoss) 

jac_w = grad_forword(w)

a = forword(w)

jac_a = grad_softmax(a)

q = stable_softmax(a)


jac_q = grad_crossE(q)

e = crossELoss(q)

print( e )

#ja = jacobian(forword, w)

#print(ja)

print(jac_w.shape)

print(jac_a.shape)

print(jac_q.shape)



1.4438475
(2, 2, 2, 2)
(2, 2, 2, 2)
(2, 2)
