In [ ]:
# https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html
# https://jax.readthedocs.io/en/latest/jax.html#jax.jacfwd   grad 只能对标量求导，jacfwd 对向量 

In [10]:

# import numpy as np
# import torch
# from torch import tensor

# from torch.autograd.functional import jacobian
# from torch.functional import Tensor

import jax
import jax.numpy as jnp
from jax import grad, jit, vmap
from jax import random

key = random.PRNGKey(0)


# def exp_reducer(x):
#     return x.exp() # .sum(dim=1)

# inputs =  Tensor( [ [1, 2], [3, 4] ] ) # torch.rand(2, 2)
# outputs = exp_reducer(inputs)

# ja = jacobian(exp_reducer, inputs)


w = jax.random.uniform(key, shape=(2, 2))   # 2*2 权重

x = jnp.array(
    [ [0, 0], 
      [0, 1] ]
    ) 

b = jax.random.uniform(key, shape=(2, 2))   # 2*2 偏置

def forword(w):

    # 前向传播 (2,2) . (2,2) = (2,2)

    a = x.dot( w ) + b

    #a = np.dot(x, w) + b 

    return a

# grad_forword = grad(forword) # grad 只能对标量求导

grad_forword = jax.jacfwd(forword)  # column-by-column
  # jacrev is row-by-row




print( grad_forword(w) )

#ja = jacobian(forword, w)

#print(ja)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [1. 0.]]

  [[0. 0.]
   [0. 1.]]]]
